In [6]:
#Brodcasting Very Important Topice 
import numpy as np
a =np.arange(6).reshape(2,3)
b =np.arange(6,12).reshape(2,3)
print(a,"a")
print(b,"b")

print(a+b)


[[0 1 2]
 [3 4 5]] a
[[ 6  7  8]
 [ 9 10 11]] b
[[ 6  8 10]
 [12 14 16]]  A+B 

In [7]:
a = np.arange(12).reshape(4,3)
b = np.arange(3)
print(a)
print(b)
print(a+b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[0 1 2]
[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]
 [ 9 11 13]]


In [9]:
a=np.arange(12).reshape(3,4)
b=np.arange(3)
print(a)
print(b)
print(a+b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 1 2]


ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [14]:
a=np.arange(3).reshape(1,3)
b=np.arange(3).reshape(3,1)
print(a+b)
 

 

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [16]:
a=np.arange(3).reshape(1,3)
b=np.arange(4).reshape(4,1)

print(a)
print(b)

print(a+b)

[[0 1 2]]
[[0]
 [1]
 [2]
 [3]]
[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]]


In [18]:
a= np.arange(12).reshape(3,4)
b = np.arange(12).reshape(4,3)

print(a+b)

ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 

In [19]:
a= np.arange(16).reshape(4,4)
b = np.arange(4).reshape(2,2)

print(a+b)

ValueError: operands could not be broadcast together with shapes (4,4) (2,2) 

In [23]:
#Working with mathematical formula
#
a= np.arange(10)
np.sin(a)

 

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [28]:
#Sigmoid
#mean Squared error
#categorical cross entrog
def sigmoid(array):
    return  1/(1 + np.exp(-(array)))
a=np.arange(100)
sigmoid(a)

array([0.5       , 0.73105858, 0.88079708, 0.95257413, 0.98201379,
       0.99330715, 0.99752738, 0.99908895, 0.99966465, 0.99987661,
       0.9999546 , 0.9999833 , 0.99999386, 0.99999774, 0.99999917,
       0.99999969, 0.99999989, 0.99999996, 0.99999998, 0.99999999,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.     

In [31]:
#Mean squalr error(n-n)Hole square
actual = np.random.randint(1,50,25)
predicted=np.random.randint(1,50,25)




In [32]:
predicted

array([12,  2, 21, 34, 47, 20, 22,  4, 30,  5, 36, 41, 47, 32,  2, 41, 36,
       21, 46, 28, 39,  3,  1, 40, 22], dtype=int32)

In [33]:
actual

array([33, 45, 39, 45, 41,  9, 46, 22, 44, 43, 28, 10, 15, 34, 25, 40, 26,
       10, 10, 10, 14, 15, 22, 28, 15], dtype=int32)

In [34]:
def mse(actual,predicted):
    return np.mean(actual-predicted)**2
mse(actual,predicted)
    
    


np.float64(2.1904)

In [ ]:
#Binary Cross ENtropy/Log 
 #Homework

In [35]:
#Working with Missing values
a = np.array([1,2,3,4,np.nan,6])
a

array([ 1.,  2.,  3.,  4., nan,  6.])

In [36]:
np.isnan(a) #True is represent missing value

array([False, False, False, False,  True, False])

In [38]:
a[~np.isnan(a)]  # missing values removed 

array([1., 2., 3., 4., 6.])

In [41]:
#Plotting Graphs
#poting a 20 plot 
#x=y
import matplotlib.pyplot as plt
x=np.linspace(-10,10,100)
y=x
y
plt.plot(x,y)

ModuleNotFoundError: No module named 'matplotlib'