In [2]:
#np.array[]
import numpy as np

#1d array
a = np.array([1,2,3])
print(a)

#Vector

[1 2 3]


In [3]:
#2d And 3d array
b= np.array([[1,2,3],[4,5,6]])
print(b)

#Matrix

[[1 2 3]
 [4 5 6]]


In [4]:
#3d Nup
#Tensor Array
c=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [6]:
#Data type. 

np.array([1,0,3],dtype=bool)

array([ True, False,  True])

In [7]:
np.array([1,0,3],dtype=complex)

array([1.+0.j, 0.+0.j, 3.+0.j])

In [9]:
np.array([1.1,0.3,3.4],dtype=float)

array([1.1, 0.3, 3.4])

In [13]:
#np.arange()
np.arange(1,11)




array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [21]:
#wITH rESHAPE
np.arange(1,13).reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [27]:
#NP.ONES AND NP.ZEROS
#It is used for Initialise where ever , it used in basically in Neural Networks
np.ones((3,4))


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [26]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [28]:
# it will provide a random value 
#np.random()
np.random.random((3,4))




array([[0.38130088, 0.07274395, 0.11336864, 0.92389213],
       [0.1260739 , 0.8953601 , 0.2589668 , 0.73589733],
       [0.10356007, 0.55525578, 0.98644167, 0.79185218]])

In [32]:
#np.linspace  (Linear space ) linearly sperable points, Use case , => ploting some graph,
np.linspace(-10,10,10,dtype=int)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [31]:
#np.identity  It is same as Identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [38]:
#Array Attributes 
#1.Ndim() Dimession 
#2.shape  > Har Dimesons ka number of items batata hai
#3.size > total number of items batata hai
#4.itemsize > har item memory me kitna space occupied kar rhaa hai ye batata hai
#5.dtype > tells the data type of each attributes



a1= np.arange(10)
a2= np.arange(12,dtype=float).reshape(3,4)
a3= np.arange(8).reshape(2,2,2)
 
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [40]:
#ndim
# it will tell you the dimension of that array
a2.ndim

2

In [41]:
#shape
a2.shape

(3, 4)

In [42]:
print(a3.shape)
a3  

#first 2 is telling that how many dimensions , 2nd and 3rd 2 is tellin number of rows and columns in that dimensions


(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [45]:
#a3.size
a3.size

8

In [44]:
print(a2.size)
a2

12


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [49]:
#itemsize

a1.itemsize

8

In [50]:
#dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)


int64
float64
int64


In [51]:
#Changing Datatype
a3.dtype

dtype('int64')

In [52]:
a3.astype(np.int32) #ye data ka memory me space ko bachane ka kam aata hai jyse kisi ki value 64 hai per wo utan space wala hai hi nahi to isko 

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)