In [3]:
#np.array
#1D Array , Or Vactor 
import numpy as np
a = np.array([1,2,3])
print(type(a))

<class 'numpy.ndarray'>


In [4]:
 #2D Array, or Matrix
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [7]:
# 3D Array or tensor
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [12]:
#dtype
np.array([1,2,3],dtype=bool)

array([ True,  True,  True])

In [13]:
#np.arange
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [17]:
#With reshape ;isme hum ek naya array bana sakte hain 3 by 3 matrix or any 
np.arange(1,13).reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [18]:
#np.onces and np.zeros

np.ones((3,4))



array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
#NP.Random
np.random.random((3,4))

array([[0.59705398, 0.98358712, 0.265499  , 0.96328911],
       [0.50272482, 0.30472638, 0.73634719, 0.31571738],
       [0.55633106, 0.99533448, 0.29076336, 0.58869881]])

In [22]:
#np.linspace  Leanier seprable points 
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [23]:
#NP.IDENTITY
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [36]:
#ArrAttribute
#ndim
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [29]:
#ndim
a3.ndim

3

In [32]:
#shape it will tells us how many dimensons 

print(a3.shape)
a3


(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [34]:
#Size
a2.size

12

In [37]:
#Itemsize
a1.itemsize

4

In [39]:
#dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int64


In [1]:
a1*2

NameError: name 'a1' is not defined

In [3]:
import numpy as np
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [10]:
#Scalar Operations  for single number operation ,

#Arithmetice 
# a2+2 #a1*2 #a1+2
a2**2

array([[144, 169, 196, 225],
       [256, 289, 324, 361],
       [400, 441, 484, 529]])

In [12]:
#Relational 

# a2 > 15
# a2==15
a2<19



array([[ True,  True,  True,  True],
       [ True,  True,  True, False],
       [False, False, False, False]])

In [13]:
#Vector Operations or Tensor
a1+a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [14]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [15]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [19]:
#Array Functions
a1=np.random.random((3,3))
a1=np.round(a1*100)
a1

array([[95., 13., 76.],
       [59.,  6., 95.],
       [33.,  6., 79.]])

In [20]:
#max /Min/ Sum / Prod
#0 => Col and 1 -> row
np.sum(a1)

np.float64(462.0)

In [21]:
np.prod(a1)

np.float64(49374157575600.0)

In [22]:
#0 => Col and 1 -> row
np.prod(a1,axis=0)

array([1.84965e+05, 4.68000e+02, 5.70380e+05])

In [29]:
#Mean/Median / std/ Var
# np.var(a1,axis=1)
#np.median(a1,axis=1)
# np.mean(a1,axis=1)
np.std(a1,axis=1)

array([35.04600152, 36.5543735 , 30.13672547])

In [30]:
#Trigonamoetric functions
np.sin(a1)

array([[ 0.68326171,  0.42016704,  0.56610764],
       [ 0.63673801, -0.2794155 ,  0.68326171],
       [ 0.99991186, -0.2794155 , -0.44411267]])

In [32]:
#Dot Product
a2=np.arange(12).reshape(3,4)
a3=np.arange(12,24).reshape(4,3)
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [33]:
#log and exponents
np.log(a1)

array([[4.55387689, 2.56494936, 4.33073334],
       [4.07753744, 1.79175947, 4.55387689],
       [3.49650756, 1.79175947, 4.36944785]])

In [34]:
np.exp(a1)

array([[1.81123908e+41, 4.42413392e+05, 1.01480039e+33],
       [4.20121040e+25, 4.03428793e+02, 1.81123908e+41],
       [2.14643580e+14, 4.03428793e+02, 2.03828107e+34]])

In [35]:
#round/floor/ceil
np.round(np.random.random((2,3))*100)

array([[94., 28., 33.],
       [ 3., 95., 69.]])

In [36]:
np.floor(np.random.random((2,3))*100)

array([[97., 96., 92.],
       [61., 68., 52.]])

In [38]:
np.ceil(np.random.random((2,3))*100)

array([[34., 49., 73.],
       [62., 46., 11.]])

In [39]:
#Indexing and slicing 
a1= np.arange(10)
a2=np.arange(12).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [41]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [44]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [45]:
#a2 [row,colum,How Much Jump distance]

np.int64(6)

In [47]:
a2[1,0]

np.int64(4)

In [49]:
a3 

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [50]:
a3[0,1,0]

np.int64(2)

In [51]:
a3[1,1,0]

np.int64(6)

In [52]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
#slicing 1d
a1[2:5:2]

array([2, 4])

In [56]:
#2d
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [57]:
a2[0,:]

array([0, 1, 2, 3])

In [59]:
a2[:,0]

array([0, 4, 8])

In [60]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [64]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [67]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [69]:
a2[1,::3]

array([4, 7])

In [71]:
a2[0:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [72]:
a3=np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [75]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [76]:
a3[0,1,:]

array([3, 4, 5])

In [77]:
a3[1,:,1]

array([10, 13, 16])

In [78]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [79]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [80]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [81]:
#iterating
a1 
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [82]:
a2
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [83]:
a3 
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [84]:
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [85]:
#Transpose

a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [86]:
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [88]:
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [89]:
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [92]:
#Stacking
#Horizontaly,
 
a4= np.arange(12).reshape(3,4)
a5=np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [94]:
#Horizontaly stcking
np.hstack((a4,a5,a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15,  0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19,  4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23,  8,  9, 10, 11, 20, 21, 22, 23]])

In [95]:
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [96]:
#Spliting split ko bich me se katta hai 
np.hsplit(a4,2)


[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [97]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]