In [3]:
#np.array
#1D Array , Or Vactor 
import numpy as np
a = np.array([1,2,3])
print(type(a))

<class 'numpy.ndarray'>


In [4]:
 #2D Array, or Matrix
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [7]:
# 3D Array or tensor
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [12]:
#dtype
np.array([1,2,3],dtype=bool)

array([ True,  True,  True])

In [13]:
#np.arange
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [17]:
#With reshape ;isme hum ek naya array bana sakte hain 3 by 3 matrix or any 
np.arange(1,13).reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [18]:
#np.onces and np.zeros

np.ones((3,4))



array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
#NP.Random
np.random.random((3,4))

array([[0.59705398, 0.98358712, 0.265499  , 0.96328911],
       [0.50272482, 0.30472638, 0.73634719, 0.31571738],
       [0.55633106, 0.99533448, 0.29076336, 0.58869881]])

In [22]:
#np.linspace  Leanier seprable points 
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [23]:
#NP.IDENTITY
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [36]:
#ArrAttribute
#ndim
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [29]:
#ndim
a3.ndim

3

In [32]:
#shape it will tells us how many dimensons 

print(a3.shape)
a3


(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [34]:
#Size
a2.size

12

In [37]:
#Itemsize
a1.itemsize

4

In [39]:
#dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int64
