In [13]:
import numpy as np 



TypeError: array() takes from 1 to 2 positional arguments but 5 were given

In [9]:
a.shape


(3,)

In [15]:
#numpy > unsigned object()



In [19]:
x=np.array([9,5,6],ndmin=3)
x

array([[[9, 5, 6]]])

In [20]:
#Zeros
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [22]:
np.full((3,3),12,dtype=int)

array([[12, 12, 12],
       [12, 12, 12],
       [12, 12, 12]])

In [23]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [24]:
np.diag([3,5,0,6,5])

array([[3, 0, 0, 0, 0],
       [0, 5, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 6, 0],
       [0, 0, 0, 0, 5]])

In [25]:
np.arange(4,50)

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
       21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
       38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [26]:
#linsapce
np.linspace(sv,ev,how many times to devide)

SyntaxError: invalid syntax. Perhaps you forgot a comma? (1612739334.py, line 2)

In [27]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [29]:
np.linspace(1,20)

array([ 1.        ,  1.3877551 ,  1.7755102 ,  2.16326531,  2.55102041,
        2.93877551,  3.32653061,  3.71428571,  4.10204082,  4.48979592,
        4.87755102,  5.26530612,  5.65306122,  6.04081633,  6.42857143,
        6.81632653,  7.20408163,  7.59183673,  7.97959184,  8.36734694,
        8.75510204,  9.14285714,  9.53061224,  9.91836735, 10.30612245,
       10.69387755, 11.08163265, 11.46938776, 11.85714286, 12.24489796,
       12.63265306, 13.02040816, 13.40816327, 13.79591837, 14.18367347,
       14.57142857, 14.95918367, 15.34693878, 15.73469388, 16.12244898,
       16.51020408, 16.89795918, 17.28571429, 17.67346939, 18.06122449,
       18.44897959, 18.83673469, 19.2244898 , 19.6122449 , 20.        ])

In [30]:
np.linspace(1,20,80)

array([ 1.        ,  1.24050633,  1.48101266,  1.72151899,  1.96202532,
        2.20253165,  2.44303797,  2.6835443 ,  2.92405063,  3.16455696,
        3.40506329,  3.64556962,  3.88607595,  4.12658228,  4.36708861,
        4.60759494,  4.84810127,  5.08860759,  5.32911392,  5.56962025,
        5.81012658,  6.05063291,  6.29113924,  6.53164557,  6.7721519 ,
        7.01265823,  7.25316456,  7.49367089,  7.73417722,  7.97468354,
        8.21518987,  8.4556962 ,  8.69620253,  8.93670886,  9.17721519,
        9.41772152,  9.65822785,  9.89873418, 10.13924051, 10.37974684,
       10.62025316, 10.86075949, 11.10126582, 11.34177215, 11.58227848,
       11.82278481, 12.06329114, 12.30379747, 12.5443038 , 12.78481013,
       13.02531646, 13.26582278, 13.50632911, 13.74683544, 13.98734177,
       14.2278481 , 14.46835443, 14.70886076, 14.94936709, 15.18987342,
       15.43037975, 15.67088608, 15.91139241, 16.15189873, 16.39240506,
       16.63291139, 16.87341772, 17.11392405, 17.35443038, 17.59

In [40]:
import time as t 
st=t.time()
l=[]
for y in range(1,1000000):
    l.append(y*2)
et=t.time()
print(et-st)


0.12735199928283691


In [41]:
l=[]
for y in range(1,10):
    l.append(y*2)
print(l)

[2, 4, 6, 8, 10, 12, 14, 16, 18]


In [43]:
import time as t 
st= t.time()
x=np.arange(1,1000000)*2
et=t.time()
print(et-st)

0.0060253143310546875


In [45]:
#
x=[2,3]+4
x

TypeError: can only concatenate list (not "int") to list

In [46]:
x=[3,5]
np.add(x,4)


array([7, 9])

In [48]:
y=[0,4]
y

[0, 4]

In [49]:
x=y.reshape(3,3)


AttributeError: 'list' object has no attribute 'reshape'

In [50]:
s=np.arange(12)


In [51]:
arr[:2,1:,:2]

NameError: name 'arr' is not defined

In [52]:
#get eleement from an array an thata are divisibel by 5 and 6,5 or 6
(x%5==0)&(x%7==0)

TypeError: unsupported operand type(s) for %: 'list' and 'int'

In [54]:
x=np.arange(0,12).reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [55]:
x1=np.array([[3,4,5,7,8,9,0]])
x2=np.array([[4,0,10,12,3,8,6]])
x1

array([[3, 4, 5, 7, 8, 9, 0]])