In [12]:
#Q-1 Create a null vector of size 10 but the fifth value which is 1.
import numpy as np
vak= np.zeros(10 ,dtype=int)
vak[4::5]=1
vak

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 1])

In [15]:
# Q-2 Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.
a = int(input("Enter Number Of rows(a): "))
b = int(input("Enter Number of Colums(b): "))

array = np.random.rand(a,b) #Shape (a,b) Random array
avg = np.mean(array)

print("Random array :")
print(array)
print("Average of array:",avg)

Enter Number Of rows(a):  3
Enter Number of Colums(b):  4


Random array :
[[0.19090692 0.43140124 0.86155264 0.07215964]
 [0.33568158 0.29436495 0.30152344 0.26431325]
 [0.78951556 0.12116725 0.14140754 0.79954729]]
Average of array: 0.3836284421138656


In [27]:
#Numpy array vs python Lists\
#Speed
#list
import time
a = [i for i in range(10000000)]
b = [ i for i in range(10000000,200000000)]

c=[]

start = time.time()
for i in range(len(a)):
    c.append(a[i]+b[i])
print(time.time()-start)


3.1441454887390137


In [25]:
 
2.22/0.04

55.50000000000001

In [24]:
#Numpy 
import numpy as np
a = np.arange(10000000)
b = np.arange(10000000,20000000)
start = time.time()
c = a + b
print(time.time()-start)

0.04758286476135254


In [ ]:
# Numpy Array is more faster then python List 

In [28]:
#Built in python data type List 
# Terms of Memory 
a = [i for i in range(10000000)]
import sys

sys.getsizeof(a)

89095160

In [33]:
#Numpy 
a = np.arange(10000000, dtype=np.int8)
sys.getsizeof(a)

10000112

In [ ]:
# numpy much better then python built in datatype in because it use less memory 


In [34]:
#Advance Indexing 
a = np.arange(12).reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [35]:
a[1,2]

np.int64(5)

In [36]:
 
a[::2]

array([[0, 1, 2],
       [6, 7, 8]])

In [37]:
# Fancy Indexing
a[[0,2,3]]

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [38]:
a = np.arange(24).reshape(6,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [39]:
a[[0,2,3,5]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [20, 21, 22, 23]])

In [40]:
a[:,[0,2,3]]

array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11],
       [12, 14, 15],
       [16, 18, 19],
       [20, 22, 23]])

In [41]:
# Boolean Indexing
a = np.random.randint(1,100,24).reshape(6,4)
a

array([[29,  4,  4, 73],
       [72, 16, 97, 31],
       [57, 43, 45, 60],
       [29, 32, 48, 71],
       [96, 68, 56, 86],
       [81, 57, 90,  8]], dtype=int32)

In [42]:
a >50

array([[False, False, False,  True],
       [ True, False,  True, False],
       [ True, False, False,  True],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True, False]])

In [43]:
a[a>50]

array([73, 72, 97, 57, 60, 71, 96, 68, 56, 86, 81, 57, 90], dtype=int32)

In [45]:
#find our even numbers
a[a%2 ==0]

array([ 4,  4, 72, 16, 60, 32, 48, 96, 68, 56, 86, 90,  8], dtype=int32)

In [47]:
a[(a>50)&(a%2==0)]

array([72, 60, 96, 68, 56, 86, 90], dtype=int32)

In [49]:
a [~(a % 7 == 0)]

array([29,  4,  4, 73, 72, 16, 97, 31, 57, 43, 45, 60, 29, 32, 48, 71, 96,
       68, 86, 81, 57, 90,  8], dtype=int32)

In [ ]:
#Broadcasting

# The term brodacsting describes how Numpy treats array wtih diffrent shapes during arithmentic operations
# the smallarray i s"bradcast " across the larger arrrya so that they have compitable shapes.
    

In [50]:
a = np.arange(6).reshape(2,3)
b= np.arange(6,12).reshape(2,3)

print(a)
print(b)
print(a+b)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]
[[ 6  8 10]
 [12 14 16]]
